"""initial migration

Revision ID: 0d2ea216ee9e
Revises: 5c13ee889aa3
Create Date: 2025-06-10 16:15:00.501458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2ea216ee9e'
down_revision: Union[str, None] = '5c13ee889aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_index(op.f('ix_contact_message'), 'contact', ['message'], unique=False)
    op.create_index(op.f('ix_contact_status'), 'contact', ['status'], unique=False)
    op.create_index(op.f('ix_contact_subject'), 'contact', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_subject'), table_name='contact')
    op.drop_index(op.f('ix_contact_status'), table_name='contact')
    op.drop_index(op.f('ix_contact_message'), table_name='contact')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
