"""add column to services table

Revision ID: 59a3b32c246e
Revises: fa0ae92d562d
Create Date: 2025-06-21 12:13:02.702743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3b32c246e'
down_revision: Union[str, None] = 'fa0ae92d562d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_column('services', 'slug')
    # ### end Alembic commands ###
