"""Add User model

Revision ID: 893eec55402f
Revises: ab7e67df78f8
Create Date: 2025-06-26 22:40:36.976463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893eec55402f'
down_revision: Union[str, None] = 'ab7e67df78f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('getintouchs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_getintouchs_created_at'), 'getintouchs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_getintouchs_created_at'), table_name='getintouchs')
    op.drop_column('getintouchs', 'created_at')
    # ### end Alembic commands ###
