"""Add Getintouch table

Revision ID: ab7e67df78f8
Revises: ba4a51578082
Create Date: 2025-06-26 22:26:11.360427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7e67df78f8'
down_revision: Union[str, None] = 'ba4a51578082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('getintouchs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_getintouchs_email'), 'getintouchs', ['email'], unique=False)
    op.create_index(op.f('ix_getintouchs_id'), 'getintouchs', ['id'], unique=False)
    op.create_index(op.f('ix_getintouchs_message'), 'getintouchs', ['message'], unique=False)
    op.create_index(op.f('ix_getintouchs_name'), 'getintouchs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_getintouchs_name'), table_name='getintouchs')
    op.drop_index(op.f('ix_getintouchs_message'), table_name='getintouchs')
    op.drop_index(op.f('ix_getintouchs_id'), table_name='getintouchs')
    op.drop_index(op.f('ix_getintouchs_email'), table_name='getintouchs')
    op.drop_table('getintouchs')
    # ### end Alembic commands ###
