"""Add testimonial model

Revision ID: ee84a5ae0f70
Revises: 5c4f223ebc87
Create Date: 2025-06-21 20:19:36.699768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee84a5ae0f70'
down_revision: Union[str, None] = '5c4f223ebc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonial_description'), 'testimonial', ['description'], unique=False)
    op.create_index(op.f('ix_testimonial_id'), 'testimonial', ['id'], unique=False)
    op.create_index(op.f('ix_testimonial_name'), 'testimonial', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonial_name'), table_name='testimonial')
    op.drop_index(op.f('ix_testimonial_id'), table_name='testimonial')
    op.drop_index(op.f('ix_testimonial_description'), table_name='testimonial')
    op.drop_table('testimonial')
    # ### end Alembic commands ###
